### PR TITLE
Add action :delete

### PR DESCRIPTION
**Pull request by kplimack**
also added the option to specify :region, mostly so I can test this with test-kitchen on my laptop.

### CODE REVIEW

**Comment by kplimack** [comment]
@gosuri - ping?

**Comment by gosuri** [comment]
LGTM! Thanks so much!

**Comment by kplimack** [comment]
i'm working on getting restore/copy from snapshot to work, but the docs for
aws-sdk are just the autogenerated stubs, nothing helpful at all

**Comment by gosuri** [comment]
Yeah, the docs are poor. I've been also meaning to get to using test-kitchen at some point.

**Pull request merged**
